# See @https://laravel.com/docs/11.x/pint#running-tests-on-github-actions
name: Laravel Pint

on:
  push:
    branches:
      - main

jobs:

  laravel-pint:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write # Necessary to comment on PRs
      actions: write       # Necessary to cancel workflow executions
      packages: write
      deployments: write
      statuses: write
      contents: write

    steps:
      # See @https://github.com/marketplace/actions/checkout
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      # See @https://github.com/marketplace/actions/setup-php-action
      - name: Setup
        uses: ./.github/actions/setup # Use the local action
        with:
            php-version: "8.3"
            php-extensions: "json, dom, curl, libxml, mbstring"

      - name: Install Laravel Pint
        run: composer global require laravel/pint

      - name: Run Pint
        run: pint

      - name: Push Changes Back to the Repo
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add .
          git commit -m "Laravel Pint: Fixes coding style" || exit 0
          git push
