name: Run Laravel Tests

on: pull_request

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:7.4
        ports:
          - 6379:6379

      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: laravel
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        ports:
          - 3306:3306

    steps:
      # See @https://github.com/marketplace/actions/checkout
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup # Use the local action
        with:
            php-version: "8.3"
            coverage: xdebug

      - name: Install Composer Dependencies
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Copy .env File
        run: cp .env.example .env

      - name: Generate an App Key
        run: php artisan key:generate

      - name: Run Tests
        # env:
        #   DB_CONNECTION: sqlite
        #   DB_DATABASE: ":memory:"
        run: php artisan test --compact --coverage --min=75
