name: Run Laravel Tests

on: pull_request

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:7.4
        ports:
          - 6379:6379

      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: laravel
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        ports:
          - 3306:3306

    env:
      PHP_VERSION: "8.3"
      PHP_EXTENSIONS: dom, curl, libxml, mbstring, zip, pcntl, pdo, gd, redis,igbinary,msgpack,lzf,zstd,lz4,memcached
      EXT_CACHE_KEY: cache-v1 # can be any string, change to clear the extension cache.

    steps:
      # See @https://github.com/marketplace/actions/checkout
      - name: Checkout Code
        uses: actions/checkout@v4

      # See @https://github.com/shivammathur/cache-extensions?tab=readme-ov-file#workflow
      - name: Setup cache environment
        id: extcache
        uses: shivammathur/cache-extensions@v1
        with:
          php-version: ${{ env.PHP_VERSION }}
          extensions: ${{ env.PHP_EXTENSIONS }}
          key: ${{ env.EXT_CACHE_KEY }}

      - name: Cache extensions
        uses: actions/cache@v4.1.2
        with:
          path: ${{ steps.extcache.outputs.dir }}
          key: ${{ steps.extcache.outputs.key }}
          restore-keys: ${{ steps.extcache.outputs.key }}

      # See @https://github.com/marketplace/actions/setup-php-action
      - name: Setup PHP and Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          extensions: ${{ env.PHP_EXTENSIONS }}
          tools: composer:v2

      # See @https://github.com/marketplace/actions/setup-php-action#cache-composer-dependencies
      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache Dependencies
        uses: actions/cache@v4.1.2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer

      - name: Install Composer Dependencies
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Copy .env File
        run: cp .env.example .env

      - name: Generate an App Key
        run: php artisan key:generate

      - name: Run Tests
        # env:
        #   DB_CONNECTION: sqlite
        #   DB_DATABASE: ":memory:"
        run: php artisan test --compact
